name: custom-mobs
version: '${project.version}'
main: com.draconincdomain.custommobs.CustomMobsControl
api-version: '1.20'
commands:
  custommob:
    description: "Will spawn a custom entity from the custom mob enum"
    usage: "/custommob"
    permission: custommobs.admin
  customreload:
    description: "Will reload the mob config values"
    usage: "/reloadcustom"
    permission: custommobs.admin
  entitycount:
    description: "Will show the count of spawned entities"
    usage: "/entitycount"
    permission: custommobs.admin
  example:
    description: "Example command"
    usage: "/example"
    permission: custommobs.admin
