name: custom-mobs
version: '${project.version}'
main: com.draconincdomain.custommobs.CustomMobsControl
api-version: '1.20'
commands:
  customspawn:
    description: "Will spawn a custom entity from the custom mob enum"
    usage: "/customspawn"
    permission: custommobs.admin
  customreload:
    description: "Will reload the mob config values"
    usage: "/reloadcustom"
    permission: custommobs.admin
